### ISSUE TITLE
Здравствуйте, прошу помощи в настройке mqtt для Home Assistant

### ISSUE THREAD

**Issue by dennismora** [v-vadim/Ballu_ASP-100#1]
Не могли бы вы поподробнее рассказать как подключали бризер. Этот yaml нужно же как-то в бризер закинуть? Как вы это сделали, как к нему подключились? Там на сколько я знаю ESP, если так - то какая, не в курсе?

**Comment by v-vadim** [comment]
Этот yaml

**Comment by v-vadim** [comment]
Обновил readme
