### ISSUE TITLE
Счем связано ограничение в версии Mosqitto

### ISSUE THREAD

**Issue by MrMeison** [v-vadim/Ballu_ASP-100#2]
Привет!
Можешь пожалуйста расскрыть мысль с чем связано ограничение в версии mqtt брокера? 

> настроить MQTT брокер EMQX или Mosquitto 1.5.11

**Comment by v-vadim** [comment]
В Mosquitto старше версий 1.5.11 внесены изменения в SSL/TLS. Где то встречал обсуждения внесения изменений в код Mosquitto, для поддержки аутентификации, но более подробно не разбирался, так как Mosquitto я не использую. Если вы используете Mosquitto, как addon в HA, то можете попробовать Mosquitto Fix https://github.com/SharkyRawr/hass-mqtt-fix. Но данный фикс нарушает безопасность сервера Mosquitto

**Comment by MrMeison** [comment]
Большое спасибо, буду пробовать! Насколько я понял это больше про анонимный вход и игнорирование SSL.
для связаности 
- https://4pda.to/forum/index.php?showtopic=1076299&view=findpost&p=132178110

Кстати, судя по [changelog](https://github.com/eclipse-mosquitto/mosquitto/blob/master/ChangeLog.txt) версии 1.5.11 нет, возможно стоит поправить.
