### ISSUE TITLE
Датчик PM2.5

### ISSUE THREAD

**Issue by plax1988** [v-vadim/Ballu_ASP-100#3]
Датчик PM2.5
      - device: # Датчик PM2.5
          identifiers: e465b82b6450
        name: "PM2.5"
        unique_id: "ballu_asp100_e465b82b6450_PM2"
        enabled_by_default: false
        state_topic: "rusclimate/<device_type>/<device_id>/state/sensor/pm2"
        unit_of_measurement: "mkg/m3"
        icon: mdi:chemical-weapon

**Comment by v-vadim** [comment]
Что у вас за бризер и какой датчик? Так как со стандартным датчиком таких топиков нет. Да и датчик MH-Z19 не может такого определять

**Comment by plax1988** [comment]
Добрый день. 
ONEAIR ASP-200. 
Думал они только производительностью отличаются внутри. 
Почитал доку, оказывается еще и датчиками.
![image](https://github.com/user-attachments/assets/83a460eb-6d30-48a7-b05d-76258764816d)
my fault.
