### ISSUE TITLE
Ресурс фильтра не Int

### ISSUE THREAD

**Issue by plax1988** [v-vadim/Ballu_ASP-100#4]
У меня ресурс фильтра писал в логе, что не INT, хотя проблема погла быть с локалью.
Пришлось ',' на '.' менять
value_template: "{{ value.replace('[','').replace(']','').replace(',','.') }}"

**Comment by v-vadim** [comment]
В топике ресурса фильтра данные выводятся в виде "[100]"  там нет запятых 
![Снимок](https://github.com/user-attachments/assets/1abca209-1f43-491a-a411-8a4f1f575654)
Покажите ваш скриншот топика с ресурсом фильтра

**Comment by plax1988** [comment]
Добрый день
Возможно дело в другой версии прошики.
![image](https://github.com/user-attachments/assets/b93921c4-8728-43d9-b4fd-82ca6e5ab01c)
В приложении Hommyn показыает целое число.

**Comment by william-aqn** [comment]
Это [ресурс фильтра, ресурс пре-фильтра] в s200, там как раз прошивка 1.15 сейчас актуальная.
Сделал форк, отладил - работает
https://github.com/william-aqn/Ballu_ASP-200/blob/main/ballu_asp_200.yaml#L172

+ добавил вывод pm2 датчика
