### ISSUE TITLE
Таймер турбо режима

### ISSUE THREAD

**Issue by 9112745148** [v-vadim/Ballu_ASP-100#6]
Для отображения таймера в минутах и секундах необходимо дополнить код и привести к следующему виду:
- device: # Таймер турбо режима
           identifiers: <MAC>
        name: "Turbo mode timer"
        unique_id: "ballu_asp100_<MAC>_timertm"
        enabled_by_default: false
        state_topic: "rusclimate/<device_type>/<device_id>/state/time"
        value_template: '{{ value | int | timestamp_custom("%M:%S") }}'
        icon: mdi:timer

**Comment by v-vadim** [comment]
Обновил
